version: "3"

services:

  ui:
    build: .
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: camino.local
      VIRTUAL_PORT: ${NODE_PORT}
    expose:
      - ${NODE_PORT}

networks:
  default:
    external:
      name: nginx-proxy