version: "3"

services:

  app:
    build: .
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: camino.pw
      VIRTUAL_PORT: ${NODE_PORT}
      LETSENCRYPT_HOST: camino.pw
      LETSENCRYPT_EMAIL: francoisromain@gmail.com
    expose:
      - ${NODE_PORT}

networks:
  default:
    external:
      name: nginx-proxy